# Generated by Django 2.2.12 on 2022-02-01 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_name', models.CharField(max_length=250, unique=True, verbose_name='doküman ismi')),
                ('documents_metadata', models.TextField(blank=True, null=True, verbose_name='doküman metadata')),
                ('documents_doc', models.FileField(upload_to='static/', verbose_name='yüklenen doküman')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_sentence', models.CharField(blank=True, max_length=200, null=True, verbose_name='arama cümlesi')),
                ('SearchHistory_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Documents', verbose_name='doküman')),
            ],
        ),
    ]
