# Generated by Django 2.2.12 on 2021-12-18 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='ders adı')),
                ('documents_title', models.CharField(max_length=250, unique=True, verbose_name='proje başlığı')),
                ('documents_summary', models.TextField(blank=True, null=True, verbose_name='proje özeti')),
                ('documents_term', models.CharField(blank=True, max_length=30, null=True, verbose_name='proje dönemi')),
                ('documents_doc', models.FileField(upload_to='static/', verbose_name='yüklenecek tez')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yükleyen kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='öğrenci adı')),
                ('student_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='öğrenci numarası')),
                ('student_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documents', verbose_name='tez adı')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=50, null=True, verbose_name='anahtar kelime')),
                ('keyword_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documents', verbose_name='tez adı')),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='görevi')),
                ('lecturer_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='ünvanı')),
                ('lecturer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='görevlinin adı')),
                ('is_consultant', models.BooleanField(default=False, verbose_name='danışman mı')),
                ('jury_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documents', verbose_name='tez adı')),
            ],
        ),
    ]
