# Generated by Django 2.2.12 on 2022-02-06 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('docID', models.UUIDField(default=documents.models.generate_uuid, editable=False, unique=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=documents.models.get_file_path)),
                ('query', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=200, null=True, verbose_name='arama cümlesi')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('documentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Documents', verbose_name='doküman')),
            ],
        ),
    ]
