# Generated by Django 2.2.12 on 2022-02-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='searchhistory',
            old_name='documentID',
            new_name='document',
        ),
    ]
