# Generated by Django 2.2.12 on 2022-02-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documents_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='search_sentence',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='arama cümlesi'),
        ),
    ]
