# Generated by Django 2.2.12 on 2022-02-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documents_search_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='documents_name',
            field=models.CharField(max_length=250, verbose_name='doküman ismi'),
        ),
    ]
