# Generated by Django 2.2.12 on 2022-02-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20220205_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='admin_user',
            new_name='userID',
        ),
    ]
