# Generated by Django 2.2.12 on 2022-02-05 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20220205_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='SearchHistory_documents',
            new_name='documentID',
        ),
        migrations.RenameField(
            model_name='searchhistory',
            old_name='search_sentence',
            new_name='query',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='documents_doc',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='documents_metadata',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='documents_name',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='search_sentence',
        ),
        migrations.AddField(
            model_name='documents',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='path',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='query',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
