# Generated by Django 2.2.24 on 2022-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='resultDocID',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='resultDocPath',
            field=models.TextField(blank=True, null=True),
        ),
    ]
