# Generated by Django 2.2.24 on 2022-03-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20220228_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='resultPageList',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='resultTotalObject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='resultTotalPage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
