# Generated by Django 2.2.24 on 2022-03-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20220304_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='resultTotalImage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
