# Generated by Django 2.2.24 on 2022-03-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_searchhistory_resulttotalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='resultMessage',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
