# Generated by Django 2.2.12 on 2022-02-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]


    def insertData(apps, schema_editor):
        User = apps.get_model('users', 'User')
        user = User(username = "admin", first_name = "admin", last_name = "user", email = "admin@foid.com", is_superuser = True, is_admin = True, password = "pbkdf2_sha256$150000$UkCYFYQohwSd$fEZaQnTsTkDEAa/4A5lJHP1m1LB36oIW3Wdk82m5V3Y=")
        user.save()


    operations = [
        migrations.RunPython(insertData),
    ]